"""Build independently authored, fully developed cards for ranks 11-50."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "canonical" / "frequency-0011-0050.jsonl"


CARDS = [
    (11, "nicht", "negation particle", "not",
     [{"position": "before the element negated or near the end when negating the clause"}],
     ("Die Bibliothek ist heute nicht geöffnet.", "The library is not open today."),
     [("Ich trinke keinen Kaffee, aber der Tee ist nicht schlecht.", "I do not drink coffee, but the tea is not bad."),
      ("Der Termin ist nicht am Dienstag, sondern am Mittwoch.", "The appointment is not on Tuesday but on Wednesday."),
      ("Bitte sprich nicht so schnell.", "Please do not speak so quickly.")],
     "Nicht negates verbs, adjectives, adverbs, phrases, or a whole clause. Use kein rather than nicht directly before an indefinite noun."),
    (12, "es", "personal / impersonal pronoun", "it; there",
     [{"case": "nominative / accusative", "form": "es"}, {"use": "impersonal subject", "examples": "weather, time, fixed expressions"}],
     ("Es regnet seit dem frühen Morgen.", "It has been raining since early morning."),
     [("Wo ist mein Handy? Ich finde es nicht.", "Where is my phone? I cannot find it."),
      ("Im Dorf gibt es eine kleine Bäckerei.", "There is a small bakery in the village."),
      ("Es ist schon halb neun.", "It is already half past eight.")],
     "Es can refer to a neuter noun, serve as an impersonal subject, or appear in fixed expressions such as es gibt."),
    (13, "mit", "dative preposition", "with; by",
     [{"case": "dative"}, {"contractions": "mit dem, mit der; no standard article contraction"}],
     ("Am Wochenende wandern wir mit unseren Nachbarn.", "At the weekend we go hiking with our neighbors."),
     [("Schneide das Papier mit einer Schere.", "Cut the paper with scissors."),
      ("Fährst du mit dem Fahrrad zur Arbeit?", "Do you ride your bicycle to work?"),
      ("Mit achtzehn zog Selma nach Köln.", "At eighteen Selma moved to Cologne.")],
     "Mit always takes dative. It commonly marks accompaniment, means, manner, or the age at which something happens."),
    (14, "sich", "reflexive pronoun", "oneself; himself; herself; themselves",
     [{"person": "3rd person / formal", "accusative": "sich", "dative": "sich"}, {"related forms": "mich, dich, uns, euch"}],
     ("Leon setzt sich ans Fenster.", "Leon sits down by the window."),
     [("Die beiden kennen sich seit der Schule.", "The two have known each other since school."),
      ("Frau Weber wäscht sich die Hände.", "Ms. Weber washes her hands."),
      ("Er erinnert sich gern an die Reise.", "He likes remembering the trip.")],
     "Sich is the third-person and formal reflexive pronoun in both accusative and dative. With plural subjects it can also express each other."),
    (15, "er", "personal pronoun", "he; him",
     [{"case": "nominative", "form": "er"}, {"case": "accusative", "form": "ihn"}, {"case": "dative", "form": "ihm"}, {"possessive_stem": "sein-"}],
     ("Paul bleibt zu Hause, weil er Fieber hat.", "Paul is staying home because he has a fever."),
     [("Kennst du den Mann dort? Ich sehe ihn oft im Park.", "Do you know the man over there? I often see him in the park."),
      ("Der Arzt gibt ihm ein neues Rezept.", "The doctor gives him a new prescription."),
      ("Der Tisch ist alt, aber er ist noch stabil.", "The table is old, but it is still sturdy.")],
     "Er is nominative masculine singular and can refer to a male person or a masculine noun. Use ihn in the accusative and ihm in the dative."),
    (16, "auf", "two-way preposition", "on; onto; at",
     [{"use": "location", "case": "dative"}, {"use": "destination", "case": "accusative"}],
     ("Auf dem Balkon wachsen frische Kräuter.", "Fresh herbs grow on the balcony."),
     [("Stell die Gläser bitte auf das Regal.", "Please put the glasses on the shelf."),
      ("Wir warten auf den nächsten Zug.", "We are waiting for the next train."),
      ("Auf Wiedersehen, bis nächste Woche!", "Goodbye, see you next week!")],
     "Auf takes dative for location and accusative for a destination. Some verbs and fixed expressions govern auf plus accusative."),
    (17, "für", "accusative preposition", "for",
     [{"case": "accusative"}, {"contraction": "fürs = für das (informal/common)"}],
     ("Dieses Paket ist für meinen Bruder.", "This package is for my brother."),
     [("Danke für deine schnelle Antwort.", "Thank you for your quick reply."),
      ("Wir bleiben für drei Tage in Hamburg.", "We are staying in Hamburg for three days."),
      ("Sie hält den Plan für sinnvoll.", "She considers the plan sensible.")],
     "Für always takes accusative. It can mark a recipient, purpose, exchange, duration, or judgment in expressions such as etwas für gut halten."),
    (18, "auch", "adverb / focus particle", "also; too; even",
     [{"position": "usually close to the word or phrase it includes"}],
     ("Mein Cousin lernt auch Deutsch.", "My cousin is learning German too."),
     [("Auch kleine Schritte bringen uns weiter.", "Even small steps move us forward."),
      ("Sie kommt aus Bremen und wohnt auch dort.", "She comes from Bremen and lives there as well."),
      ("Kann ich auch mitkommen?", "Can I come along too?")],
     "Auch adds another item or highlights an included case. Its position helps show exactly what also, too, or even applies to."),
    (19, "an", "two-way preposition", "at; on; to",
     [{"use": "location", "case": "dative"}, {"use": "destination", "case": "accusative"}, {"contractions": "am = an dem; ans = an das"}],
     ("An der Wand hängt eine alte Uhr.", "An old clock hangs on the wall."),
     [("Häng deinen Mantel an den Haken.", "Hang your coat on the hook."),
      ("Am Freitag beginnt der Kurs.", "The course begins on Friday."),
      ("Mila schreibt eine Nachricht an ihre Mutter.", "Mila writes a message to her mother.")],
     "An takes dative for location and accusative for a destination. It also appears with days, vertical surfaces, recipients, and many governed verbs."),
    (20, "dass", "subordinating conjunction", "that",
     [{"word_order": "the conjugated verb normally goes to the end of the subordinate clause"}],
     ("Ich hoffe, dass der Laden noch geöffnet ist.", "I hope that the shop is still open."),
     [("Es stimmt, dass Amir morgen beginnt.", "It is true that Amir starts tomorrow."),
      ("Sie sagt, dass sie später zurückkommt.", "She says that she will come back later."),
      ("Wir freuen uns, dass ihr dabei seid.", "We are happy that you are joining us.")],
     "Dass introduces a subordinate content clause and sends its conjugated verb to the end. Do not confuse it with the relative pronoun das."),
    (21, "zu", "dative preposition / infinitive marker / adverb", "to; too",
     [{"preposition": "takes dative"}, {"contractions": "zum = zu dem; zur = zu der"}, {"infinitive": "zu + infinitive"}],
     ("Nach der Arbeit gehe ich direkt zum Supermarkt.", "After work I go straight to the supermarket."),
     [("Es ist zu dunkel zum Lesen.", "It is too dark for reading."),
      ("Nina versucht, früher aufzustehen.", "Nina tries to get up earlier."),
      ("Mach bitte die Tür zu.", "Please close the door.")],
     "As a preposition, zu takes dative and often marks a destination. It also marks many infinitives, means too before an adjective, and can mean closed."),
    (22, "als", "subordinating conjunction / comparative marker", "when; than; as",
     [{"past event": "als + subordinate clause"}, {"comparison": "comparative + als"}, {"role": "als + noun"}],
     ("Als ich klein war, wohnte ich auf dem Land.", "When I was little, I lived in the countryside."),
     [("Der neue Weg ist kürzer als der alte.", "The new route is shorter than the old one."),
      ("Tarek arbeitet als Krankenpfleger.", "Tarek works as a nurse."),
      ("Sie öffnete das Fenster, als der Regen aufhörte.", "She opened the window when the rain stopped.")],
     "Als introduces a single past time, follows comparatives with the meaning than, and identifies a role or function with the meaning as."),
    (23, "können", "modal verb", "can; to be able to",
     [{"present": "kann, kannst, kann, können, könnt, können"}, {"simple_past": "konnte, konntest, konnte, konnten, konntet, konnten"}, {"past_participle": "gekonnt; double infinitive with another verb"}],
     ("Meine Tochter kann schon allein lesen.", "My daughter can already read by herself."),
     [("Könnt ihr das bitte wiederholen?", "Can you please repeat that?"),
      ("Wegen des Nebels konnten wir kaum etwas sehen.", "Because of the fog, we could hardly see anything."),
      ("Das kann durchaus stimmen.", "That may well be true.")],
     "Können expresses ability, possibility, or permission. With another verb, that infinitive normally stands at the end of a main clause."),
    (24, "dies", "demonstrative determiner / pronoun", "this; these",
     [{"stem": "dies-"}, {"endings": "declines broadly like the definite article: dieser, diese, dieses, diesen, diesem"}],
     ("Dieses Buch gehört meiner Mitbewohnerin.", "This book belongs to my roommate."),
     [("In dieser Straße gibt es viele Cafés.", "There are many cafés on this street."),
      ("Diesen Fehler mache ich oft.", "I often make this mistake."),
      ("Welchen Pullover möchtest du? Diesen hier.", "Which sweater would you like? This one here.")],
     "Dies- points to a particular person or thing and takes case, gender, and number endings similar to the definite article."),
    (25, "wie", "question word / conjunction", "how; like; as",
     [{"question": "asks about manner, condition, or degree"}, {"comparison": "so ... wie = as ... as"}],
     ("Wie komme ich von hier zum Rathaus?", "How do I get from here to city hall?"),
     [("Wie war der Film gestern Abend?", "How was the film last night?"),
      ("Die Suppe schmeckt fast wie bei meiner Oma.", "The soup tastes almost like my grandmother's."),
      ("Der Koffer ist so schwer wie meiner.", "The suitcase is as heavy as mine.")],
     "Wie asks how and introduces equal comparisons or similarities. Unequal comparisons after a comparative normally use als, not wie."),
    (26, "wir", "personal pronoun", "we",
     [{"case": "nominative", "form": "wir"}, {"case": "accusative / dative", "form": "uns"}, {"possessive_stem": "unser-"}],
     ("Wir treffen uns um sechs vor dem Theater.", "We are meeting at six in front of the theater."),
     [("Morgen besuchen uns unsere Großeltern.", "Our grandparents are visiting us tomorrow."),
      ("Der Lehrer erklärt uns die neue Regel.", "The teacher explains the new rule to us."),
      ("Unser Garten ist dieses Jahr besonders grün.", "Our garden is especially green this year.")],
     "Wir is the nominative first-person plural pronoun. Uns serves as both accusative and dative, and the related possessive stem is unser-."),
    (27, "ihr", "personal / possessive pronoun", "you (plural); her; their",
     [{"personal": "ihr (nominative), euch (accusative/dative)"}, {"possessive": "ihr- = her/their; Ihr- = your (formal)"}, {"dative_of_sie": "ihr = to her"}],
     ("Kommt ihr heute Abend zur Feier?", "Are you all coming to the party this evening?"),
     [("Ich schicke euch morgen die Fotos.", "I will send you all the photos tomorrow."),
      ("Jana sucht ihre Brille.", "Jana is looking for her glasses."),
      ("Die Studierenden zeigen ihre Ausweise.", "The students show their ID cards.")],
     "Lowercase ihr has several roles: informal plural you, to her, or the possessive stem for her and their. Context and endings identify the role."),
    (28, "so", "adverb / particle", "so; like this; such",
     [{"comparison": "so ... wie = as ... as"}, {"degree": "so + adjective/adverb"}],
     ("Warum bist du heute so leise?", "Why are you so quiet today?"),
     [("Dreh den Griff so, nicht andersherum.", "Turn the handle like this, not the other way around."),
      ("So ein schönes Geschenk habe ich nicht erwartet.", "I did not expect such a beautiful gift."),
      ("Der Weg ist nicht so weit, wie er aussieht.", "The route is not as far as it looks.")],
     "So can indicate manner, degree, or a result already understood from context. It also forms equal comparisons with wie."),
    (29, "bei", "dative preposition", "at; near; with; during",
     [{"case": "dative"}, {"contraction": "beim = bei dem"}],
     ("Meine Schlüssel liegen bei der Eingangstür.", "My keys are by the front door."),
     [("Ruth wohnt noch bei ihren Eltern.", "Ruth still lives with her parents."),
      ("Beim Essen sprechen wir selten über die Arbeit.", "While eating, we rarely talk about work."),
      ("Bei starkem Wind bleibt die Fähre im Hafen.", "In strong winds, the ferry stays in the harbor.")],
     "Bei always takes dative. It can mean at someone's place, near, during, or under a particular condition."),
    (30, "sein", "possessive determiner / pronoun", "his; its",
     [{"stem": "sein-"}, {"endings": "like ein: sein, seine, seinen, seinem, seiner"}],
     ("David holt seinen Sohn von der Schule ab.", "David picks up his son from school."),
     [("Der Hund schläft in seinem Korb.", "The dog is sleeping in its basket."),
      ("Oskar hat seine Fahrkarte verloren.", "Oskar has lost his ticket."),
      ("Jedes Gerät hat seine eigene Nummer.", "Each device has its own number.")],
     "Possessive sein- means his or its and takes endings like ein. Its form agrees with the possessed noun, not with the owner."),
    (31, "aber", "coordinating conjunction / particle", "but; however",
     [{"word_order": "does not change normal main-clause order"}],
     ("Die Wohnung ist klein, aber sehr hell.", "The apartment is small but very bright."),
     [("Ich würde gern kommen, aber ich muss arbeiten.", "I would like to come, but I have to work."),
      ("Das ist aber eine Überraschung!", "Well, that is a surprise!"),
      ("Der Mantel war teuer, hielt aber viele Jahre.", "The coat was expensive but lasted many years.")],
     "Aber contrasts words, phrases, or clauses without changing main-clause word order. As a particle, it can add surprise or emphasis."),
    (32, "man", "indefinite pronoun", "one; you; people; they",
     [{"case": "nominative", "form": "man"}, {"accusative": "einen"}, {"dative": "einem"}, {"possessive": "sein-"}],
     ("In diesem Museum darf man nicht fotografieren.", "You are not allowed to take photos in this museum."),
     [("Man sagt, der Winter werde mild.", "They say the winter will be mild."),
      ("Im Urlaub lernt man oft neue Leute kennen.", "On vacation, you often meet new people."),
      ("So etwas kann einem überall passieren.", "Something like that can happen to anyone anywhere.")],
     "Man refers to people in general and always takes a third-person singular verb. Its object forms are einen and einem."),
    (33, "noch", "adverb / particle", "still; yet; another; more",
     [{"time": "continuation or something not completed"}, {"addition": "one more / additional"}],
     ("Der Bäcker hat noch geöffnet.", "The bakery is still open."),
     [("Hast du deine Bewerbung noch nicht abgeschickt?", "Have you not sent your application yet?"),
      ("Wir brauchen noch zwei Stühle.", "We need two more chairs."),
      ("Es ist spät, doch ich bin noch wach.", "It is late, but I am still awake.")],
     "Noch often marks continuation or something expected but not completed. With quantities it means another or more."),
    (34, "nach", "dative preposition / adverb", "after; to; according to",
     [{"case": "dative"}, {"destinations": "cities, most countries, directions, and home"}, {"time": "after"}],
     ("Nach dem Mittagessen machen wir einen Spaziergang.", "After lunch we take a walk."),
     [("Im April fliegt Elena nach Portugal.", "In April Elena flies to Portugal."),
      ("Der Bus fährt nach Norden.", "The bus is heading north."),
      ("Meiner Meinung nach ist der Preis fair.", "In my opinion, the price is fair.")],
     "Nach takes dative and commonly means after. It marks destinations without an article, directions, and standards or viewpoints."),
    (35, "oder", "coordinating conjunction", "or",
     [{"word_order": "does not change normal main-clause order"}],
     ("Möchtest du Wasser oder Saft?", "Would you like water or juice?"),
     [("Wir können laufen oder den Bus nehmen.", "We can walk or take the bus."),
      ("Rufst du mich an, oder soll ich dir schreiben?", "Will you call me, or should I write to you?"),
      ("Du wohnst doch in Leipzig, oder?", "You live in Leipzig, right?")],
     "Oder presents alternatives without changing main-clause word order. At the end of a statement, oder? asks for confirmation."),
    (36, "all", "indefinite determiner / pronoun", "all; every",
     [{"forms": "all, alle, aller, allen, allem; endings depend on case, gender, and number"}],
     ("Alle Fenster im Haus sind geöffnet.", "All the windows in the house are open."),
     [("Wir wünschen dir alles Gute.", "We wish you all the best."),
      ("Nach all der Arbeit braucht sie Ruhe.", "After all that work, she needs rest."),
      ("Der Schnee ist in aller Ruhe geschmolzen.", "The snow melted without any fuss.")],
     "All- refers to a complete set or amount and declines for case, gender, and number. Alles is the common neuter pronoun meaning everything."),
    (37, "aus", "dative preposition", "out of; from; made of",
     [{"case": "dative"}],
     ("Sofia nimmt eine Flasche aus dem Kühlschrank.", "Sofia takes a bottle out of the refrigerator."),
     [("Mein Nachbar kommt aus der Schweiz.", "My neighbor comes from Switzerland."),
      ("Der Ring ist aus Silber.", "The ring is made of silver."),
      ("Aus Angst sagte das Kind kein Wort.", "Out of fear, the child did not say a word.")],
     "Aus always takes dative. It marks movement from inside, origin, material, or a motivating cause."),
    (38, "was", "interrogative / relative pronoun", "what; which",
     [{"question": "was"}, {"prepositional question": "wo(r)- + preposition, e.g. womit, worauf"}, {"relative": "after alles, etwas, nichts, or a whole clause"}],
     ("Was möchtest du zum Frühstück essen?", "What would you like to eat for breakfast?"),
     [("Womit öffnet man diese Dose?", "What do you use to open this can?"),
      ("Er hat alles gefunden, was er suchte.", "He found everything he was looking for."),
      ("Was für Musik hörst du gern?", "What kind of music do you like listening to?")],
     "Was asks about things or information. With prepositions, standard German usually uses wo(r)- compounds, and was can introduce certain relative clauses."),
    (39, "nur", "adverb / focus particle", "only; just",
     [{"position": "usually directly before or close to the element being limited"}],
     ("Das Geschäft nimmt nur Bargeld.", "The shop only accepts cash."),
     [("Ich habe nur eine kurze Frage.", "I just have one quick question."),
      ("Keine Sorge, das war nur ein Witz.", "Do not worry, that was only a joke."),
      ("Wenn du nur früher angerufen hättest!", "If only you had called earlier!")],
     "Nur limits a quantity, choice, or statement and usually stands near what it restricts. In wishes, wenn ... nur can mean if only."),
    (40, "sagen", "verb", "to say; to tell",
     [{"present": "sage, sagst, sagt, sagen, sagt, sagen"}, {"simple_past": "sagte"}, {"past_participle": "gesagt"}, {"pattern": "jemandem etwas sagen (dative person, accusative thing)"}],
     ("Kannst du mir bitte deinen Namen sagen?", "Can you please tell me your name?"),
     [("Mara sagt, dass sie keine Zeit hat.", "Mara says that she has no time."),
      ("Was hast du gerade gesagt?", "What did you just say?"),
      ("Der Blick auf die Zahlen sagt viel über die Lage aus.", "A look at the figures says a lot about the situation.")],
     "Sagen reports words or information. The person told is normally dative, while the thing said is accusative or a clause."),
    (41, "dann", "adverb", "then; in that case",
     [{"word_order": "when first, the conjugated verb follows immediately"}],
     ("Zuerst räumen wir auf, dann kochen wir.", "First we tidy up, then we cook."),
     [("Wenn du müde bist, geh dann früh ins Bett.", "If you are tired, then go to bed early."),
      ("Bis dann, wir sehen uns am Montag.", "See you then; we will see each other on Monday."),
      ("Was machen wir denn dann?", "What will we do then?")],
     "Dann points to a later step or a consequence. At the beginning of a main clause, it is followed directly by the conjugated verb."),
    (42, "wenn", "subordinating conjunction", "if; when; whenever",
     [{"word_order": "conjugated verb at the end of the subordinate clause"}, {"time": "present, future, or repeated events"}],
     ("Wenn das Wetter gut ist, essen wir draußen.", "If the weather is good, we eat outside."),
     [("Ruf mich an, wenn du angekommen bist.", "Call me when you have arrived."),
      ("Wenn ich gestresst war, ging ich am Fluss spazieren.", "Whenever I was stressed, I went for a walk by the river."),
      ("Was wäre, wenn der Zug ausfiele?", "What would happen if the train were canceled?")],
     "Wenn introduces conditions and present, future, or repeated times. For a single event in the past, use als."),
    (43, "müssen", "modal verb", "must; to have to",
     [{"present": "muss, musst, muss, müssen, müsst, müssen"}, {"simple_past": "musste"}, {"past_participle": "gemusst; double infinitive with another verb"}],
     ("Ich muss morgen sehr früh aufstehen.", "I have to get up very early tomorrow."),
     [("Müsst ihr am Feiertag arbeiten?", "Do you have to work on the public holiday?"),
      ("Wir mussten wegen einer Baustelle umkehren.", "We had to turn around because of roadworks."),
      ("Du musst das nicht sofort entscheiden.", "You do not have to decide that immediately.")],
     "Müssen expresses necessity. Nicht müssen means do not have to; it does not mean must not, which is usually nicht dürfen."),
    (44, "um", "two-way preposition / conjunction", "around; at; in order to",
     [{"place": "accusative for around"}, {"time": "accusative in clock times"}, {"purpose": "um ... zu + infinitive"}],
     ("Um acht Uhr beginnt die Vorstellung.", "The performance begins at eight o'clock."),
     [("Die Kinder sitzen um den runden Tisch.", "The children are sitting around the round table."),
      ("Wir gehen um das Gebäude herum.", "We walk around the building."),
      ("Lukas spart Geld, um ein Motorrad zu kaufen.", "Lukas is saving money in order to buy a motorcycle.")],
     "Um takes accusative for clock times and movement or position around something. Um ... zu introduces a purpose when both clauses share a subject."),
    (45, "ja", "response / modal particle", "yes; as you know; indeed",
     [{"response": "ja"}, {"particle": "adds shared knowledge, emphasis, or surprise"}],
     ("Ja, ich komme gern mit.", "Yes, I would be happy to come along."),
     [("Du kennst den Weg ja schon.", "You already know the way, as you know."),
      ("Das ist ja unglaublich!", "That is unbelievable!"),
      ("Er hat ja gesagt, also können wir anfangen.", "He said yes, so we can begin.")],
     "Ja answers a yes-no question affirmatively. Unstressed inside a sentence, it is a modal particle whose exact effect depends on context."),
    (46, "kein", "negative determiner / pronoun", "no; not a; none",
     [{"stem": "kein-"}, {"endings": "like ein: kein, keine, keinen, keinem, keiner"}],
     ("Im Schrank ist kein sauberes Glas.", "There is no clean glass in the cupboard."),
     [("Heute fährt kein Bus zum Flughafen.", "No bus goes to the airport today."),
      ("Ich habe keine Geschwister.", "I do not have any siblings."),
      ("Welcher Schlüssel passt? Keiner.", "Which key fits? None of them.")],
     "Kein- negates a noun that would otherwise have no article or an indefinite article. It declines like ein and can also stand alone."),
    (47, "über", "two-way preposition / adverb", "over; above; about",
     [{"use": "location", "case": "dative"}, {"use": "destination / crossing", "case": "accusative"}, {"topic": "usually accusative"}],
     ("Über dem Esstisch hängt eine Lampe.", "A lamp hangs above the dining table."),
     [("Ein Flugzeug fliegt über die Stadt.", "An airplane is flying over the city."),
      ("Wir sprechen über unseren Urlaub.", "We are talking about our vacation."),
      ("Die Temperatur liegt heute über dreißig Grad.", "The temperature is above thirty degrees today.")],
     "Über takes dative for a fixed location and accusative for movement across or a topic. It can also express a quantity above a limit."),
    (48, "da", "adverb / subordinating conjunction", "there; since; because",
     [{"place": "there"}, {"conjunction": "conjugated verb at the end of the subordinate clause"}, {"compounds": "da(r)- + preposition, e.g. damit, darauf"}],
     ("Deine Jacke liegt da auf dem Stuhl.", "Your jacket is there on the chair."),
     [("Da der Aufzug kaputt ist, nehmen wir die Treppe.", "Since the elevator is broken, we are taking the stairs."),
      ("Plötzlich war das Licht wieder da.", "Suddenly the light was back on."),
      ("Damit bin ich völlig einverstanden.", "I completely agree with that.")],
     "Da points to a place or to something present. As a conjunction it can mean since or because, and it forms compounds that refer to things."),
    (49, "geben", "verb", "to give; there is/are",
     [{"present": "gebe, gibst, gibt, geben, gebt, geben"}, {"simple_past": "gab"}, {"past_participle": "gegeben"}, {"pattern": "jemandem etwas geben"}],
     ("Die Verkäuferin gibt dem Kunden eine Quittung.", "The saleswoman gives the customer a receipt."),
     [("Gibst du mir bitte das Salz?", "Could you please pass me the salt?"),
      ("Nächstes Jahr wird es hier einen neuen Kindergarten geben.", "Next year there will be a new daycare center here."),
      ("Der Apfelbaum gibt im Herbst viel Obst.", "The apple tree produces a lot of fruit in autumn.")],
     "Geben usually takes a dative recipient and an accusative thing. The fixed expression es gibt means there is or there are and takes accusative."),
    (50, "vor", "two-way preposition / adverb", "in front of; before; ago",
     [{"use": "location", "case": "dative"}, {"use": "destination", "case": "accusative"}, {"time / cause": "usually dative"}],
     ("Vor dem Bahnhof wartet ein Taxi.", "A taxi is waiting in front of the train station."),
     [("Stell den Karton vor die Kellertür.", "Put the box in front of the basement door."),
      ("Vor einer Woche begann die Ausstellung.", "The exhibition began a week ago."),
      ("Der Junge zitterte vor Kälte.", "The boy was shivering from the cold.")],
     "Vor takes dative for location and accusative for a destination. With dative it also commonly means before, ago, or because of a strong reaction."),
]


def build() -> list[dict]:
    rows = []
    for rank, target, pos, meaning, forms, main, extras, note in CARDS:
        rows.append({
            "schema_version": 2,
            "semantic_id": f"de-DE:{pos.replace(' ', '-').replace('/', '-')}:"
                           f"{target}:{rank:04}",
            "sequence": 10000 + rank,
            "frequency_rank": rank,
            "target": target,
            "lemma": target,
            "sense_id": f"core-{rank:04}",
            "part_of_speech": pos,
            "meaning": meaning,
            "forms": forms,
            "german_sentence": main[0],
            "english_sentence": main[1],
            "literal_translation": "",
            "example_focus": "core uses",
            "extra_examples": [
                {"german": german, "english": english}
                for german, english in extras
            ],
            "usage_note": note,
            "register": "neutral",
            "variety": "Germany Standard German",
            "sentence_audio": "",
            "text_status": "draft_complete_pending_human_review",
            "locked_fields": [],
            "created_for": "first-500 frequency curriculum",
        })
    return rows


def main() -> None:
    rows = build()
    OUT.write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows),
        encoding="utf-8",
    )
    print(f"Wrote {len(rows)} cards to {OUT}")


if __name__ == "__main__":
    main()
