"""Build independently authored, fully developed cards for ranks 1-10."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/canonical/frequency-0001-0010.jsonl"

# r, target, POS, meaning, forms, main pair, extra pairs, usage note
CARDS = [
(1,"der","definite article","the",[{"gender":"masculine","nom":"der","acc":"den","dat":"dem","gen":"des"},{"gender":"feminine","nom":"die","acc":"die","dat":"der","gen":"der"},{"gender":"neuter","nom":"das","acc":"das","dat":"dem","gen":"des"},{"gender":"plural","nom":"die","acc":"die","dat":"den","gen":"der"}],("Der Schlüssel liegt auf dem Tisch.","The key is on the table."),[("Ich sehe den Bus schon.","I can already see the bus."),("Sie hilft dem neuen Nachbarn.","She helps the new neighbor."),("Die Kinder spielen im Garten.","The children are playing in the garden.")],"The definite article agrees with gender, number, and case. Learn nouns with their nominative article, but expect the article to change in a sentence."),
(2,"und","coordinating conjunction","and",[],("Mara kauft Brot und Käse.","Mara buys bread and cheese."),[("Der Kaffee ist heiß und stark.","The coffee is hot and strong."),("Wir öffnen das Fenster und warten.","We open the window and wait."),("Jonas und Lea wohnen hier.","Jonas and Lea live here.")],"Und joins words, phrases, or main clauses without changing normal main-clause word order."),
(3,"in","two-way preposition","in; into",[{"use":"location","case":"dative"},{"use":"destination","case":"accusative"}],("Die Milch steht im Kühlschrank.","The milk is in the refrigerator."),[("Wir gehen in die Küche.","We are going into the kitchen."),("Im Sommer schwimmt sie oft im See.","In summer she often swims in the lake."),("Er legt die Karte in den Umschlag.","He puts the card into the envelope.")],"In takes dative for a location and accusative for movement toward a destination. Im means in dem; ins means in das."),
(4,"sein","verb / auxiliary","to be",[{"tense":"present","forms":"bin, bist, ist, sind, seid, sind"},{"tense":"simple past","forms":"war, warst, war, waren, wart, waren"},{"past_participle":"gewesen"}],("Meine Schwester ist heute müde.","My sister is tired today."),[("Wir sind seit Montag in Berlin.","We have been in Berlin since Monday."),("Als Kind war ich sehr ruhig.","As a child, I was very quiet."),("Der Zug ist schon abgefahren.","The train has already departed.")],"Sein is highly irregular. It also forms the perfect tense of many verbs of motion or change of state."),
(5,"ein","indefinite article / pronoun","a; an; one",[{"gender":"masculine","nom":"ein","acc":"einen","dat":"einem","gen":"eines"},{"gender":"feminine","nom":"eine","acc":"eine","dat":"einer","gen":"einer"},{"gender":"neuter","nom":"ein","acc":"ein","dat":"einem","gen":"eines"}],("Vor dem Haus steht ein Fahrrad.","There is a bicycle in front of the house."),[("Nora bestellt einen Tee.","Nora orders a tea."),("Er spricht mit einer Kollegin.","He is speaking with a colleague."),("Eins der Fenster ist offen.","One of the windows is open.")],"Ein has no plural article form. Its endings follow the same pattern as possessives such as mein and dein; alone, it can mean one."),
(6,"haben","verb / auxiliary","to have",[{"tense":"present","forms":"habe, hast, hat, haben, habt, haben"},{"tense":"simple past","forms":"hatte, hattest, hatte, hatten, hattet, hatten"},{"past_participle":"gehabt"}],("Wir haben noch genug Zeit.","We still have enough time."),[("Hast du heute Unterricht?","Do you have class today?"),("Lina hatte gestern Kopfschmerzen.","Lina had a headache yesterday."),("Ich habe die Rechnung schon bezahlt.","I have already paid the bill.")],"Haben expresses possession and many common conditions. It forms the perfect tense of most German verbs."),
(7,"sie","personal pronoun","she; her; they; them; you (formal)",[{"referent":"feminine singular","nom":"sie","acc":"sie","dat":"ihr"},{"referent":"plural","nom":"sie","acc":"sie","dat":"ihnen"},{"referent":"formal you","nom":"Sie","acc":"Sie","dat":"Ihnen"}],("Klara kommt später; sie arbeitet noch.","Klara is coming later; she is still working."),[("Ich treffe sie vor dem Kino.","I am meeting her in front of the movie theater."),("Die Gäste sind da, aber sie warten draußen.","The guests are here, but they are waiting outside."),("Können Sie mir bitte helfen?","Could you please help me?")],"Lowercase sie can mean she, her, they, or them. Capitalized Sie means formal you and takes plural verb forms."),
(8,"werden","verb / auxiliary","to become; will; to be (passive)",[{"tense":"present","forms":"werde, wirst, wird, werden, werdet, werden"},{"tense":"simple past","forms":"wurde, wurdest, wurde, wurden, wurdet, wurden"},{"participles":"geworden (become); worden (passive)"}],("Nachmittags wird es plötzlich kalt.","In the afternoon it suddenly gets cold."),[("Ich werde dich morgen anrufen.","I will call you tomorrow."),("Die Straße wird heute gesperrt.","The road is being closed today."),("Aus dem Setzling ist ein kräftiger Baum geworden.","The seedling has grown into a strong tree.")],"Werden means become; with an infinitive it can mark future, and with a past participle it forms the event passive."),
(9,"von","dative preposition","from; of; by",[{"case":"dative"},{"contraction":"vom = von dem"}],("Der Brief ist von meiner Tante.","The letter is from my aunt."),[("Wir fahren vom Bahnhof mit dem Bus weiter.","We continue from the train station by bus."),("Das Ende von dem Film war überraschend.","The ending of the film was surprising."),("Das Fenster wurde von einem Handwerker repariert.","The window was repaired by a tradesperson.")],"Von always takes dative. It can mark origin, an of-relationship, or the agent in a passive sentence; von dem normally contracts to vom."),
(10,"ich","personal pronoun","I",[{"case":"nominative","form":"ich"},{"case":"accusative","form":"mich"},{"case":"dative","form":"mir"},{"possessive_stem":"mein-"}],("Ich brauche eine kurze Pause.","I need a short break."),[("Heute koche ich für meine Freunde.","Today I am cooking for my friends."),("Kannst du mich hören?","Can you hear me?"),("Mir ist ein bisschen kalt.","I am a little cold.")],"Ich is nominative and is not capitalized unless it begins a sentence. Use mich for accusative objects and mir for dative objects."),
]

def main():
    rows=[]
    for r,t,pos,meaning,forms,main,extras,note in CARDS:
        rows.append({"schema_version":2,"semantic_id":f"de-DE:{pos.replace(' ','-')}:{t}:{r:04}","sequence":10000+r,"frequency_rank":r,"target":t,"lemma":t,"sense_id":f"core-{r:04}","part_of_speech":pos,"meaning":meaning,"forms":forms,"german_sentence":main[0],"english_sentence":main[1],"literal_translation":"","example_focus":"core uses","extra_examples":[{"german":d,"english":e} for d,e in extras],"usage_note":note,"register":"neutral","variety":"Germany Standard German","sentence_audio":"","text_status":"draft_complete_pending_human_review","locked_fields":[],"created_for":"first-500 frequency curriculum"})
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in rows),encoding='utf-8')
    print(f"Wrote {len(rows)} cards to {OUT.relative_to(ROOT)}")

if __name__ == '__main__': main()
